/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#8A2BE2",
        "primary-dim": "#7022b8",
        "primary-container": "#2D1B4E",
        "on-primary": "#ffffff",
        "on-primary-container": "#D6BCFA",
        "secondary": "#8A2BE2",
        "secondary-container": "#2D1B4E",
        "on-secondary": "#fff7f5",
        "tertiary": "#8A2BE2",
        "tertiary-dim": "#7022b8",
        "tertiary-container": "#8A2BE2",
        "on-tertiary": "#ffffff",
        "brand-accent": "#A855F7",
        "brand-purple": "#8A2BE2",
        "surface": "#121212",
        "surface-dim": "#0e1111",
        "surface-bright": "#1E1E1E",
        "surface-container-lowest": "#151515",
        "surface-container-low": "#1E1E1E",
        "surface-container": "#1E1E1E",
        "surface-container-high": "#2A2A2A",
        "surface-container-highest": "#2A2A2A",
        "surface-variant": "#2A2A2A",
        "background": "#121212",
        "on-background": "#F2F4F4",
        "on-surface": "#F2F4F4",
        "on-surface-variant": "#D1D1D1",
        "outline": "#757c7d",
        "outline-variant": "#444444",
        "error": "#9f403d",
        "on-error": "#ffffff",
        "error-container": "#fe8983",
        "inverse-surface": "#F2F4F4",
        "inverse-on-surface": "#9c9d9d",
        "inverse-primary": "#ffffff",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Pretendard", "Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
